#!/usr/bin/env bash

set -euo pipefail

VKBASALT_DIR="$HOME/.config/vkBasalt"
INSTALL_DIR="$VKBASALT_DIR/shaders/JorelTX-ON"
CONFIG_FILE="$VKBASALT_DIR/vkBasalt.conf"
BACKUP_DIR="$VKBASALT_DIR/backups/JorelTX-ON"
TEMP_CONFIG="$VKBASALT_DIR/.JorelTX-ON-V5.conf.tmp"

echo "========================================"
echo "       JorelTX-ON V5 - Activator"
echo "========================================"
echo

echo "[1/4] Verificando instalação..."

for file in \
    "$INSTALL_DIR/Curves.fx" \
    "$INSTALL_DIR/Tonemap.fx" \
    "$INSTALL_DIR/Vibrance.fx" \
    "$INSTALL_DIR/ReShade.fxh" \
    "$INSTALL_DIR/ReShadeUI.fxh"
do
if [[ ! -f "$file" ]]; then
echo
echo "ERRO: arquivo instalado não encontrado:"
echo "  $file"
echo
echo "Execute primeiro:"
echo "  ./scripts/install.sh"
exit 1
fi
done

echo "OK: arquivos do JorelTX-ON encontrados."
echo

echo "[2/4] Procurando dependências externas..."

find_shader() {
local shader_name="$1"

local search_paths=(
    "$VKBASALT_DIR/shaders"
    "$HOME/.local/share/reshade"
    "$HOME/.local/share/reshade-shaders"
)

for base in "${search_paths[@]}"; do
    if [[ -d "$base" ]]; then
        local result
        result="$(find "$base" -type f -name "$shader_name" -print -quit 2>/dev/null || true)"

        if [[ -n "$result" ]]; then
            printf '%s\n' "$result"
            return 0
        fi
    fi
done

return 1

}

BLOOMINGHDR="${JORELTX_BLOOMINGHDR:-}"
CLARITY="${JORELTX_CLARITY:-}"

if [[ -z "$BLOOMINGHDR" ]]; then
BLOOMINGHDR="$(find_shader "BloomingHDR.fx" || true)"
fi

if [[ -z "$CLARITY" ]]; then
CLARITY="$(find_shader "Clarity.fx" || true)"
fi

if [[ -z "$BLOOMINGHDR" ]]; then
echo
echo "ERRO: BloomingHDR.fx não foi encontrado."
echo
echo "Instale o shader externamente ou informe o caminho:"
echo
echo '  export JORELTX_BLOOMINGHDR="/caminho/BloomingHDR.fx"'
echo
echo "A configuração atual NÃO foi alterada."
exit 1
fi

echo "OK: BloomingHDR.fx encontrado:"
echo "  $BLOOMINGHDR"

if [[ -z "$CLARITY" ]]; then
echo
echo "ERRO: Clarity.fx não foi encontrado."
echo
echo "Instale o shader externamente ou informe o caminho:"
echo
echo '  export JORELTX_CLARITY="/caminho/Clarity.fx"'
echo
echo "A configuração atual NÃO foi alterada."
exit 1
fi

echo "OK: Clarity.fx encontrado:"
echo "  $CLARITY"
echo

echo "[3/4] Preparando nova configuração..."

cat > "$TEMP_CONFIG" <<EOF

# JorelTX ON V5

# Generated by JorelTX ON

effects = BloomingHDR:Vibrance:Clarity:Tonemap:Curves:smaa:cas

enableOnLaunch = True

reshadeIncludePath = $INSTALL_DIR

BloomingHDR = $BLOOMINGHDR
Vibrance = $INSTALL_DIR/Vibrance.fx
Clarity = $CLARITY
Tonemap = $INSTALL_DIR/Tonemap.fx
Curves = $INSTALL_DIR/Curves.fx

casSharpness = 0.6
EOF

if [[ ! -s "$TEMP_CONFIG" ]]; then
echo
echo "ERRO: não foi possível criar a nova configuração."
rm -f "$TEMP_CONFIG"
exit 1
fi

echo "OK: nova configuração preparada."
echo

echo "[4/4] Criando backup e ativando V5..."

mkdir -p "$BACKUP_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
TIMESTAMP="$(date '+%Y%m%d-%H%M%S')"
BACKUP_FILE="$BACKUP_DIR/vkBasalt.conf.$TIMESTAMP"

cp -a "$CONFIG_FILE" "$BACKUP_FILE"

echo "Backup criado:"
echo "  $BACKUP_FILE"

fi

mv -f "$TEMP_CONFIG" "$CONFIG_FILE"

echo
echo "========================================"
echo "       JorelTX-ON V5 ativado!"
echo "========================================"
echo
echo "Configuração:"
echo "  $CONFIG_FILE"
echo
echo "Efeitos:"
echo "  BloomingHDR"
echo "  Vibrance"
echo "  Clarity"
echo "  Tonemap"
echo "  Curves"
echo "  SMAA"
echo "  CAS"
echo
echo "CAS Sharpness: 0.6"
echo
echo "Backup:"
echo "  $BACKUP_DIR"
echo
echo "Sua configuração anterior foi preservada."
echo
